#!/bin/bash
set -euo pipefail

echo
echo "Running tests..."
echo

if [ -d "testfiles" ] ; then
  rm -rf testfiles
fi

mkdir testfiles
cd testfiles

git clone https://github.com/LedgerHQ/ledger-sample-apps.git
cd ledger-sample-apps/blue-app-helloworld
git checkout 2aff840de034daa0725fb4755c851b3e9c979b87

echo
echo "Building blue-app-helloworld..."
docker run -v ${PWD}:/code ledger-sdk

echo
echo "Checking bin/app.hex checksum..."
echo "bf881e2e2473268fa44fe1c419ae005caf4f16c958f4cb3ea723be563d03b5fa  bin/app.hex" | shasum --algorithm 256 --check
