#!/bin/bash
set -euo pipefail

echo
echo "Running tests..."
echo

if [ -d "testfiles" ] ; then
  rm -rf testfiles
fi

mkdir testfiles
cd testfiles

git clone https://github.com/LedgerHQ/ledger-sample-apps.git
cd ledger-sample-apps/blue-app-helloworld
git checkout 2aff840de034daa0725fb4755c851b3e9c979b87

echo
echo "Building blue-app-helloworld..."
docker run -v ${PWD}:/code ledger-sdk

echo
echo "Checking bin/app.hex checksum..."
echo "ee5dd7653d67036aa98ecb940b411193c3c5cc58f862c8a325a12dd537350458  bin/app.hex" | shasum --algorithm 256 --check
